# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eli/Projects/Stakken

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eli/Projects/Stakken

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eli/Projects/Stakken/CMakeFiles /home/eli/Projects/Stakken//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eli/Projects/Stakken/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Stakken

# Build rule for target.
Stakken: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Stakken
.PHONY : Stakken

# fast build rule for target.
Stakken/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/build
.PHONY : Stakken/fast

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

#=============================================================================
# Target rules for targets named Client

# Build rule for target.
Client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Client
.PHONY : Client

# fast build rule for target.
Client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/build
.PHONY : Client/fast

include/gl3w.o: include/gl3w.c.o
.PHONY : include/gl3w.o

# target to build an object file
include/gl3w.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/include/gl3w.c.o
.PHONY : include/gl3w.c.o

include/gl3w.i: include/gl3w.c.i
.PHONY : include/gl3w.i

# target to preprocess a source file
include/gl3w.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/include/gl3w.c.i
.PHONY : include/gl3w.c.i

include/gl3w.s: include/gl3w.c.s
.PHONY : include/gl3w.s

# target to generate assembly for a file
include/gl3w.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/include/gl3w.c.s
.PHONY : include/gl3w.c.s

src/Application.o: src/Application.cpp.o
.PHONY : src/Application.o

# target to build an object file
src/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Application.cpp.o
.PHONY : src/Application.cpp.o

src/Application.i: src/Application.cpp.i
.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s
.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/Assets/Assets.o: src/Assets/Assets.cpp.o
.PHONY : src/Assets/Assets.o

# target to build an object file
src/Assets/Assets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Assets.cpp.o
.PHONY : src/Assets/Assets.cpp.o

src/Assets/Assets.i: src/Assets/Assets.cpp.i
.PHONY : src/Assets/Assets.i

# target to preprocess a source file
src/Assets/Assets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Assets.cpp.i
.PHONY : src/Assets/Assets.cpp.i

src/Assets/Assets.s: src/Assets/Assets.cpp.s
.PHONY : src/Assets/Assets.s

# target to generate assembly for a file
src/Assets/Assets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Assets.cpp.s
.PHONY : src/Assets/Assets.cpp.s

src/Assets/BGShader.o: src/Assets/BGShader.cpp.o
.PHONY : src/Assets/BGShader.o

# target to build an object file
src/Assets/BGShader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/BGShader.cpp.o
.PHONY : src/Assets/BGShader.cpp.o

src/Assets/BGShader.i: src/Assets/BGShader.cpp.i
.PHONY : src/Assets/BGShader.i

# target to preprocess a source file
src/Assets/BGShader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/BGShader.cpp.i
.PHONY : src/Assets/BGShader.cpp.i

src/Assets/BGShader.s: src/Assets/BGShader.cpp.s
.PHONY : src/Assets/BGShader.s

# target to generate assembly for a file
src/Assets/BGShader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/BGShader.cpp.s
.PHONY : src/Assets/BGShader.cpp.s

src/Assets/Font.o: src/Assets/Font.cpp.o
.PHONY : src/Assets/Font.o

# target to build an object file
src/Assets/Font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Font.cpp.o
.PHONY : src/Assets/Font.cpp.o

src/Assets/Font.i: src/Assets/Font.cpp.i
.PHONY : src/Assets/Font.i

# target to preprocess a source file
src/Assets/Font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Font.cpp.i
.PHONY : src/Assets/Font.cpp.i

src/Assets/Font.s: src/Assets/Font.cpp.s
.PHONY : src/Assets/Font.s

# target to generate assembly for a file
src/Assets/Font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Font.cpp.s
.PHONY : src/Assets/Font.cpp.s

src/Assets/Sound.o: src/Assets/Sound.cpp.o
.PHONY : src/Assets/Sound.o

# target to build an object file
src/Assets/Sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Sound.cpp.o
.PHONY : src/Assets/Sound.cpp.o

src/Assets/Sound.i: src/Assets/Sound.cpp.i
.PHONY : src/Assets/Sound.i

# target to preprocess a source file
src/Assets/Sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Sound.cpp.i
.PHONY : src/Assets/Sound.cpp.i

src/Assets/Sound.s: src/Assets/Sound.cpp.s
.PHONY : src/Assets/Sound.s

# target to generate assembly for a file
src/Assets/Sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Sound.cpp.s
.PHONY : src/Assets/Sound.cpp.s

src/Assets/Sounds.o: src/Assets/Sounds.cpp.o
.PHONY : src/Assets/Sounds.o

# target to build an object file
src/Assets/Sounds.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Sounds.cpp.o
.PHONY : src/Assets/Sounds.cpp.o

src/Assets/Sounds.i: src/Assets/Sounds.cpp.i
.PHONY : src/Assets/Sounds.i

# target to preprocess a source file
src/Assets/Sounds.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Sounds.cpp.i
.PHONY : src/Assets/Sounds.cpp.i

src/Assets/Sounds.s: src/Assets/Sounds.cpp.s
.PHONY : src/Assets/Sounds.s

# target to generate assembly for a file
src/Assets/Sounds.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Sounds.cpp.s
.PHONY : src/Assets/Sounds.cpp.s

src/Assets/Texture.o: src/Assets/Texture.cpp.o
.PHONY : src/Assets/Texture.o

# target to build an object file
src/Assets/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Texture.cpp.o
.PHONY : src/Assets/Texture.cpp.o

src/Assets/Texture.i: src/Assets/Texture.cpp.i
.PHONY : src/Assets/Texture.i

# target to preprocess a source file
src/Assets/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Texture.cpp.i
.PHONY : src/Assets/Texture.cpp.i

src/Assets/Texture.s: src/Assets/Texture.cpp.s
.PHONY : src/Assets/Texture.s

# target to generate assembly for a file
src/Assets/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Assets/Texture.cpp.s
.PHONY : src/Assets/Texture.cpp.s

src/Challenges/Challenges.o: src/Challenges/Challenges.cpp.o
.PHONY : src/Challenges/Challenges.o

# target to build an object file
src/Challenges/Challenges.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Challenges/Challenges.cpp.o
.PHONY : src/Challenges/Challenges.cpp.o

src/Challenges/Challenges.i: src/Challenges/Challenges.cpp.i
.PHONY : src/Challenges/Challenges.i

# target to preprocess a source file
src/Challenges/Challenges.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Challenges/Challenges.cpp.i
.PHONY : src/Challenges/Challenges.cpp.i

src/Challenges/Challenges.s: src/Challenges/Challenges.cpp.s
.PHONY : src/Challenges/Challenges.s

# target to generate assembly for a file
src/Challenges/Challenges.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Challenges/Challenges.cpp.s
.PHONY : src/Challenges/Challenges.cpp.s

src/Data/Identity.o: src/Data/Identity.cpp.o
.PHONY : src/Data/Identity.o

# target to build an object file
src/Data/Identity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Data/Identity.cpp.o
.PHONY : src/Data/Identity.cpp.o

src/Data/Identity.i: src/Data/Identity.cpp.i
.PHONY : src/Data/Identity.i

# target to preprocess a source file
src/Data/Identity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Data/Identity.cpp.i
.PHONY : src/Data/Identity.cpp.i

src/Data/Identity.s: src/Data/Identity.cpp.s
.PHONY : src/Data/Identity.s

# target to generate assembly for a file
src/Data/Identity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Data/Identity.cpp.s
.PHONY : src/Data/Identity.cpp.s

src/Game/Board.o: src/Game/Board.cpp.o
.PHONY : src/Game/Board.o

# target to build an object file
src/Game/Board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Board.cpp.o
.PHONY : src/Game/Board.cpp.o

src/Game/Board.i: src/Game/Board.cpp.i
.PHONY : src/Game/Board.i

# target to preprocess a source file
src/Game/Board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Board.cpp.i
.PHONY : src/Game/Board.cpp.i

src/Game/Board.s: src/Game/Board.cpp.s
.PHONY : src/Game/Board.s

# target to generate assembly for a file
src/Game/Board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Board.cpp.s
.PHONY : src/Game/Board.cpp.s

src/Game/ClientLobby.o: src/Game/ClientLobby.cpp.o
.PHONY : src/Game/ClientLobby.o

# target to build an object file
src/Game/ClientLobby.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/ClientLobby.cpp.o
.PHONY : src/Game/ClientLobby.cpp.o

src/Game/ClientLobby.i: src/Game/ClientLobby.cpp.i
.PHONY : src/Game/ClientLobby.i

# target to preprocess a source file
src/Game/ClientLobby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/ClientLobby.cpp.i
.PHONY : src/Game/ClientLobby.cpp.i

src/Game/ClientLobby.s: src/Game/ClientLobby.cpp.s
.PHONY : src/Game/ClientLobby.s

# target to generate assembly for a file
src/Game/ClientLobby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/ClientLobby.cpp.s
.PHONY : src/Game/ClientLobby.cpp.s

src/Game/Demo.o: src/Game/Demo.cpp.o
.PHONY : src/Game/Demo.o

# target to build an object file
src/Game/Demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Demo.cpp.o
.PHONY : src/Game/Demo.cpp.o

src/Game/Demo.i: src/Game/Demo.cpp.i
.PHONY : src/Game/Demo.i

# target to preprocess a source file
src/Game/Demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Demo.cpp.i
.PHONY : src/Game/Demo.cpp.i

src/Game/Demo.s: src/Game/Demo.cpp.s
.PHONY : src/Game/Demo.s

# target to generate assembly for a file
src/Game/Demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Demo.cpp.s
.PHONY : src/Game/Demo.cpp.s

src/Game/DemoPlayer.o: src/Game/DemoPlayer.cpp.o
.PHONY : src/Game/DemoPlayer.o

# target to build an object file
src/Game/DemoPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/DemoPlayer.cpp.o
.PHONY : src/Game/DemoPlayer.cpp.o

src/Game/DemoPlayer.i: src/Game/DemoPlayer.cpp.i
.PHONY : src/Game/DemoPlayer.i

# target to preprocess a source file
src/Game/DemoPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/DemoPlayer.cpp.i
.PHONY : src/Game/DemoPlayer.cpp.i

src/Game/DemoPlayer.s: src/Game/DemoPlayer.cpp.s
.PHONY : src/Game/DemoPlayer.s

# target to generate assembly for a file
src/Game/DemoPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/DemoPlayer.cpp.s
.PHONY : src/Game/DemoPlayer.cpp.s

src/Game/DemoRecorder.o: src/Game/DemoRecorder.cpp.o
.PHONY : src/Game/DemoRecorder.o

# target to build an object file
src/Game/DemoRecorder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/DemoRecorder.cpp.o
.PHONY : src/Game/DemoRecorder.cpp.o

src/Game/DemoRecorder.i: src/Game/DemoRecorder.cpp.i
.PHONY : src/Game/DemoRecorder.i

# target to preprocess a source file
src/Game/DemoRecorder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/DemoRecorder.cpp.i
.PHONY : src/Game/DemoRecorder.cpp.i

src/Game/DemoRecorder.s: src/Game/DemoRecorder.cpp.s
.PHONY : src/Game/DemoRecorder.s

# target to generate assembly for a file
src/Game/DemoRecorder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/DemoRecorder.cpp.s
.PHONY : src/Game/DemoRecorder.cpp.s

src/Game/Game.o: src/Game/Game.cpp.o
.PHONY : src/Game/Game.o

# target to build an object file
src/Game/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Game.cpp.o
.PHONY : src/Game/Game.cpp.o

src/Game/Game.i: src/Game/Game.cpp.i
.PHONY : src/Game/Game.i

# target to preprocess a source file
src/Game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Game.cpp.i
.PHONY : src/Game/Game.cpp.i

src/Game/Game.s: src/Game/Game.cpp.s
.PHONY : src/Game/Game.s

# target to generate assembly for a file
src/Game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Game.cpp.s
.PHONY : src/Game/Game.cpp.s

src/Game/LocalLobby.o: src/Game/LocalLobby.cpp.o
.PHONY : src/Game/LocalLobby.o

# target to build an object file
src/Game/LocalLobby.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/LocalLobby.cpp.o
.PHONY : src/Game/LocalLobby.cpp.o

src/Game/LocalLobby.i: src/Game/LocalLobby.cpp.i
.PHONY : src/Game/LocalLobby.i

# target to preprocess a source file
src/Game/LocalLobby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/LocalLobby.cpp.i
.PHONY : src/Game/LocalLobby.cpp.i

src/Game/LocalLobby.s: src/Game/LocalLobby.cpp.s
.PHONY : src/Game/LocalLobby.s

# target to generate assembly for a file
src/Game/LocalLobby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/LocalLobby.cpp.s
.PHONY : src/Game/LocalLobby.cpp.s

src/Game/Piece.o: src/Game/Piece.cpp.o
.PHONY : src/Game/Piece.o

# target to build an object file
src/Game/Piece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Piece.cpp.o
.PHONY : src/Game/Piece.cpp.o

src/Game/Piece.i: src/Game/Piece.cpp.i
.PHONY : src/Game/Piece.i

# target to preprocess a source file
src/Game/Piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Piece.cpp.i
.PHONY : src/Game/Piece.cpp.i

src/Game/Piece.s: src/Game/Piece.cpp.s
.PHONY : src/Game/Piece.s

# target to generate assembly for a file
src/Game/Piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Piece.cpp.s
.PHONY : src/Game/Piece.cpp.s

src/Game/Randomizers/SimonRandomizer.o: src/Game/Randomizers/SimonRandomizer.cpp.o
.PHONY : src/Game/Randomizers/SimonRandomizer.o

# target to build an object file
src/Game/Randomizers/SimonRandomizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Randomizers/SimonRandomizer.cpp.o
.PHONY : src/Game/Randomizers/SimonRandomizer.cpp.o

src/Game/Randomizers/SimonRandomizer.i: src/Game/Randomizers/SimonRandomizer.cpp.i
.PHONY : src/Game/Randomizers/SimonRandomizer.i

# target to preprocess a source file
src/Game/Randomizers/SimonRandomizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Randomizers/SimonRandomizer.cpp.i
.PHONY : src/Game/Randomizers/SimonRandomizer.cpp.i

src/Game/Randomizers/SimonRandomizer.s: src/Game/Randomizers/SimonRandomizer.cpp.s
.PHONY : src/Game/Randomizers/SimonRandomizer.s

# target to generate assembly for a file
src/Game/Randomizers/SimonRandomizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Randomizers/SimonRandomizer.cpp.s
.PHONY : src/Game/Randomizers/SimonRandomizer.cpp.s

src/Game/Randomizers/XoroshiroRandomizer.o: src/Game/Randomizers/XoroshiroRandomizer.cpp.o
.PHONY : src/Game/Randomizers/XoroshiroRandomizer.o

# target to build an object file
src/Game/Randomizers/XoroshiroRandomizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Randomizers/XoroshiroRandomizer.cpp.o
.PHONY : src/Game/Randomizers/XoroshiroRandomizer.cpp.o

src/Game/Randomizers/XoroshiroRandomizer.i: src/Game/Randomizers/XoroshiroRandomizer.cpp.i
.PHONY : src/Game/Randomizers/XoroshiroRandomizer.i

# target to preprocess a source file
src/Game/Randomizers/XoroshiroRandomizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Randomizers/XoroshiroRandomizer.cpp.i
.PHONY : src/Game/Randomizers/XoroshiroRandomizer.cpp.i

src/Game/Randomizers/XoroshiroRandomizer.s: src/Game/Randomizers/XoroshiroRandomizer.cpp.s
.PHONY : src/Game/Randomizers/XoroshiroRandomizer.s

# target to generate assembly for a file
src/Game/Randomizers/XoroshiroRandomizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Game/Randomizers/XoroshiroRandomizer.cpp.s
.PHONY : src/Game/Randomizers/XoroshiroRandomizer.cpp.s

src/Gamemodes/Gamemodes.o: src/Gamemodes/Gamemodes.cpp.o
.PHONY : src/Gamemodes/Gamemodes.o

# target to build an object file
src/Gamemodes/Gamemodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Gamemodes/Gamemodes.cpp.o
.PHONY : src/Gamemodes/Gamemodes.cpp.o

src/Gamemodes/Gamemodes.i: src/Gamemodes/Gamemodes.cpp.i
.PHONY : src/Gamemodes/Gamemodes.i

# target to preprocess a source file
src/Gamemodes/Gamemodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Gamemodes/Gamemodes.cpp.i
.PHONY : src/Gamemodes/Gamemodes.cpp.i

src/Gamemodes/Gamemodes.s: src/Gamemodes/Gamemodes.cpp.s
.PHONY : src/Gamemodes/Gamemodes.s

# target to generate assembly for a file
src/Gamemodes/Gamemodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Gamemodes/Gamemodes.cpp.s
.PHONY : src/Gamemodes/Gamemodes.cpp.s

src/Input/Input.o: src/Input/Input.cpp.o
.PHONY : src/Input/Input.o

# target to build an object file
src/Input/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Input/Input.cpp.o
.PHONY : src/Input/Input.cpp.o

src/Input/Input.i: src/Input/Input.cpp.i
.PHONY : src/Input/Input.i

# target to preprocess a source file
src/Input/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Input/Input.cpp.i
.PHONY : src/Input/Input.cpp.i

src/Input/Input.s: src/Input/Input.cpp.s
.PHONY : src/Input/Input.s

# target to generate assembly for a file
src/Input/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Input/Input.cpp.s
.PHONY : src/Input/Input.cpp.s

src/Input/InputProfile.o: src/Input/InputProfile.cpp.o
.PHONY : src/Input/InputProfile.o

# target to build an object file
src/Input/InputProfile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Input/InputProfile.cpp.o
.PHONY : src/Input/InputProfile.cpp.o

src/Input/InputProfile.i: src/Input/InputProfile.cpp.i
.PHONY : src/Input/InputProfile.i

# target to preprocess a source file
src/Input/InputProfile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Input/InputProfile.cpp.i
.PHONY : src/Input/InputProfile.cpp.i

src/Input/InputProfile.s: src/Input/InputProfile.cpp.s
.PHONY : src/Input/InputProfile.s

# target to generate assembly for a file
src/Input/InputProfile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Input/InputProfile.cpp.s
.PHONY : src/Input/InputProfile.cpp.s

src/Input/Keyboard.o: src/Input/Keyboard.cpp.o
.PHONY : src/Input/Keyboard.o

# target to build an object file
src/Input/Keyboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Input/Keyboard.cpp.o
.PHONY : src/Input/Keyboard.cpp.o

src/Input/Keyboard.i: src/Input/Keyboard.cpp.i
.PHONY : src/Input/Keyboard.i

# target to preprocess a source file
src/Input/Keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Input/Keyboard.cpp.i
.PHONY : src/Input/Keyboard.cpp.i

src/Input/Keyboard.s: src/Input/Keyboard.cpp.s
.PHONY : src/Input/Keyboard.s

# target to generate assembly for a file
src/Input/Keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Input/Keyboard.cpp.s
.PHONY : src/Input/Keyboard.cpp.s

src/Networking/Client.o: src/Networking/Client.cpp.o
.PHONY : src/Networking/Client.o

# target to build an object file
src/Networking/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Networking/Client.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Networking/Client.cpp.o
.PHONY : src/Networking/Client.cpp.o

src/Networking/Client.i: src/Networking/Client.cpp.i
.PHONY : src/Networking/Client.i

# target to preprocess a source file
src/Networking/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Networking/Client.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Networking/Client.cpp.i
.PHONY : src/Networking/Client.cpp.i

src/Networking/Client.s: src/Networking/Client.cpp.s
.PHONY : src/Networking/Client.s

# target to generate assembly for a file
src/Networking/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Networking/Client.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Networking/Client.cpp.s
.PHONY : src/Networking/Client.cpp.s

src/Networking/Server.o: src/Networking/Server.cpp.o
.PHONY : src/Networking/Server.o

# target to build an object file
src/Networking/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Networking/Server.cpp.o
.PHONY : src/Networking/Server.cpp.o

src/Networking/Server.i: src/Networking/Server.cpp.i
.PHONY : src/Networking/Server.i

# target to preprocess a source file
src/Networking/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Networking/Server.cpp.i
.PHONY : src/Networking/Server.cpp.i

src/Networking/Server.s: src/Networking/Server.cpp.s
.PHONY : src/Networking/Server.s

# target to generate assembly for a file
src/Networking/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Networking/Server.cpp.s
.PHONY : src/Networking/Server.cpp.s

src/Rendering/RenderGame.o: src/Rendering/RenderGame.cpp.o
.PHONY : src/Rendering/RenderGame.o

# target to build an object file
src/Rendering/RenderGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/RenderGame.cpp.o
.PHONY : src/Rendering/RenderGame.cpp.o

src/Rendering/RenderGame.i: src/Rendering/RenderGame.cpp.i
.PHONY : src/Rendering/RenderGame.i

# target to preprocess a source file
src/Rendering/RenderGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/RenderGame.cpp.i
.PHONY : src/Rendering/RenderGame.cpp.i

src/Rendering/RenderGame.s: src/Rendering/RenderGame.cpp.s
.PHONY : src/Rendering/RenderGame.s

# target to generate assembly for a file
src/Rendering/RenderGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/RenderGame.cpp.s
.PHONY : src/Rendering/RenderGame.cpp.s

src/Rendering/Renderer.o: src/Rendering/Renderer.cpp.o
.PHONY : src/Rendering/Renderer.o

# target to build an object file
src/Rendering/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/Renderer.cpp.o
.PHONY : src/Rendering/Renderer.cpp.o

src/Rendering/Renderer.i: src/Rendering/Renderer.cpp.i
.PHONY : src/Rendering/Renderer.i

# target to preprocess a source file
src/Rendering/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/Renderer.cpp.i
.PHONY : src/Rendering/Renderer.cpp.i

src/Rendering/Renderer.s: src/Rendering/Renderer.cpp.s
.PHONY : src/Rendering/Renderer.s

# target to generate assembly for a file
src/Rendering/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/Renderer.cpp.s
.PHONY : src/Rendering/Renderer.cpp.s

src/Rendering/ScreenQuad.o: src/Rendering/ScreenQuad.cpp.o
.PHONY : src/Rendering/ScreenQuad.o

# target to build an object file
src/Rendering/ScreenQuad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/ScreenQuad.cpp.o
.PHONY : src/Rendering/ScreenQuad.cpp.o

src/Rendering/ScreenQuad.i: src/Rendering/ScreenQuad.cpp.i
.PHONY : src/Rendering/ScreenQuad.i

# target to preprocess a source file
src/Rendering/ScreenQuad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/ScreenQuad.cpp.i
.PHONY : src/Rendering/ScreenQuad.cpp.i

src/Rendering/ScreenQuad.s: src/Rendering/ScreenQuad.cpp.s
.PHONY : src/Rendering/ScreenQuad.s

# target to generate assembly for a file
src/Rendering/ScreenQuad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/ScreenQuad.cpp.s
.PHONY : src/Rendering/ScreenQuad.cpp.s

src/Rendering/Shader.o: src/Rendering/Shader.cpp.o
.PHONY : src/Rendering/Shader.o

# target to build an object file
src/Rendering/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/Shader.cpp.o
.PHONY : src/Rendering/Shader.cpp.o

src/Rendering/Shader.i: src/Rendering/Shader.cpp.i
.PHONY : src/Rendering/Shader.i

# target to preprocess a source file
src/Rendering/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/Shader.cpp.i
.PHONY : src/Rendering/Shader.cpp.i

src/Rendering/Shader.s: src/Rendering/Shader.cpp.s
.PHONY : src/Rendering/Shader.s

# target to generate assembly for a file
src/Rendering/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Rendering/Shader.cpp.s
.PHONY : src/Rendering/Shader.cpp.s

src/States/ChallengePlayState.o: src/States/ChallengePlayState.cpp.o
.PHONY : src/States/ChallengePlayState.o

# target to build an object file
src/States/ChallengePlayState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/ChallengePlayState.cpp.o
.PHONY : src/States/ChallengePlayState.cpp.o

src/States/ChallengePlayState.i: src/States/ChallengePlayState.cpp.i
.PHONY : src/States/ChallengePlayState.i

# target to preprocess a source file
src/States/ChallengePlayState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/ChallengePlayState.cpp.i
.PHONY : src/States/ChallengePlayState.cpp.i

src/States/ChallengePlayState.s: src/States/ChallengePlayState.cpp.s
.PHONY : src/States/ChallengePlayState.s

# target to generate assembly for a file
src/States/ChallengePlayState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/ChallengePlayState.cpp.s
.PHONY : src/States/ChallengePlayState.cpp.s

src/States/ChallengeSelectState.o: src/States/ChallengeSelectState.cpp.o
.PHONY : src/States/ChallengeSelectState.o

# target to build an object file
src/States/ChallengeSelectState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/ChallengeSelectState.cpp.o
.PHONY : src/States/ChallengeSelectState.cpp.o

src/States/ChallengeSelectState.i: src/States/ChallengeSelectState.cpp.i
.PHONY : src/States/ChallengeSelectState.i

# target to preprocess a source file
src/States/ChallengeSelectState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/ChallengeSelectState.cpp.i
.PHONY : src/States/ChallengeSelectState.cpp.i

src/States/ChallengeSelectState.s: src/States/ChallengeSelectState.cpp.s
.PHONY : src/States/ChallengeSelectState.s

# target to generate assembly for a file
src/States/ChallengeSelectState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/ChallengeSelectState.cpp.s
.PHONY : src/States/ChallengeSelectState.cpp.s

src/States/LobbyState.o: src/States/LobbyState.cpp.o
.PHONY : src/States/LobbyState.o

# target to build an object file
src/States/LobbyState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/LobbyState.cpp.o
.PHONY : src/States/LobbyState.cpp.o

src/States/LobbyState.i: src/States/LobbyState.cpp.i
.PHONY : src/States/LobbyState.i

# target to preprocess a source file
src/States/LobbyState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/LobbyState.cpp.i
.PHONY : src/States/LobbyState.cpp.i

src/States/LobbyState.s: src/States/LobbyState.cpp.s
.PHONY : src/States/LobbyState.s

# target to generate assembly for a file
src/States/LobbyState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/LobbyState.cpp.s
.PHONY : src/States/LobbyState.cpp.s

src/States/LoginState.o: src/States/LoginState.cpp.o
.PHONY : src/States/LoginState.o

# target to build an object file
src/States/LoginState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/LoginState.cpp.o
.PHONY : src/States/LoginState.cpp.o

src/States/LoginState.i: src/States/LoginState.cpp.i
.PHONY : src/States/LoginState.i

# target to preprocess a source file
src/States/LoginState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/LoginState.cpp.i
.PHONY : src/States/LoginState.cpp.i

src/States/LoginState.s: src/States/LoginState.cpp.s
.PHONY : src/States/LoginState.s

# target to generate assembly for a file
src/States/LoginState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/LoginState.cpp.s
.PHONY : src/States/LoginState.cpp.s

src/States/MenuState.o: src/States/MenuState.cpp.o
.PHONY : src/States/MenuState.o

# target to build an object file
src/States/MenuState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/MenuState.cpp.o
.PHONY : src/States/MenuState.cpp.o

src/States/MenuState.i: src/States/MenuState.cpp.i
.PHONY : src/States/MenuState.i

# target to preprocess a source file
src/States/MenuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/MenuState.cpp.i
.PHONY : src/States/MenuState.cpp.i

src/States/MenuState.s: src/States/MenuState.cpp.s
.PHONY : src/States/MenuState.s

# target to generate assembly for a file
src/States/MenuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/MenuState.cpp.s
.PHONY : src/States/MenuState.cpp.s

src/States/RoomSelectState.o: src/States/RoomSelectState.cpp.o
.PHONY : src/States/RoomSelectState.o

# target to build an object file
src/States/RoomSelectState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/RoomSelectState.cpp.o
.PHONY : src/States/RoomSelectState.cpp.o

src/States/RoomSelectState.i: src/States/RoomSelectState.cpp.i
.PHONY : src/States/RoomSelectState.i

# target to preprocess a source file
src/States/RoomSelectState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/RoomSelectState.cpp.i
.PHONY : src/States/RoomSelectState.cpp.i

src/States/RoomSelectState.s: src/States/RoomSelectState.cpp.s
.PHONY : src/States/RoomSelectState.s

# target to generate assembly for a file
src/States/RoomSelectState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/RoomSelectState.cpp.s
.PHONY : src/States/RoomSelectState.cpp.s

src/States/SettingsState.o: src/States/SettingsState.cpp.o
.PHONY : src/States/SettingsState.o

# target to build an object file
src/States/SettingsState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/SettingsState.cpp.o
.PHONY : src/States/SettingsState.cpp.o

src/States/SettingsState.i: src/States/SettingsState.cpp.i
.PHONY : src/States/SettingsState.i

# target to preprocess a source file
src/States/SettingsState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/SettingsState.cpp.i
.PHONY : src/States/SettingsState.cpp.i

src/States/SettingsState.s: src/States/SettingsState.cpp.s
.PHONY : src/States/SettingsState.s

# target to generate assembly for a file
src/States/SettingsState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/States/SettingsState.cpp.s
.PHONY : src/States/SettingsState.cpp.s

src/Text/Font.o: src/Text/Font.cpp.o
.PHONY : src/Text/Font.o

# target to build an object file
src/Text/Font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Text/Font.cpp.o
.PHONY : src/Text/Font.cpp.o

src/Text/Font.i: src/Text/Font.cpp.i
.PHONY : src/Text/Font.i

# target to preprocess a source file
src/Text/Font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Text/Font.cpp.i
.PHONY : src/Text/Font.cpp.i

src/Text/Font.s: src/Text/Font.cpp.s
.PHONY : src/Text/Font.s

# target to generate assembly for a file
src/Text/Font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/Text/Font.cpp.s
.PHONY : src/Text/Font.cpp.s

src/UI/Node.o: src/UI/Node.cpp.o
.PHONY : src/UI/Node.o

# target to build an object file
src/UI/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Node.cpp.o
.PHONY : src/UI/Node.cpp.o

src/UI/Node.i: src/UI/Node.cpp.i
.PHONY : src/UI/Node.i

# target to preprocess a source file
src/UI/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Node.cpp.i
.PHONY : src/UI/Node.cpp.i

src/UI/Node.s: src/UI/Node.cpp.s
.PHONY : src/UI/Node.s

# target to generate assembly for a file
src/UI/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Node.cpp.s
.PHONY : src/UI/Node.cpp.s

src/UI/UI.o: src/UI/UI.cpp.o
.PHONY : src/UI/UI.o

# target to build an object file
src/UI/UI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/UI.cpp.o
.PHONY : src/UI/UI.cpp.o

src/UI/UI.i: src/UI/UI.cpp.i
.PHONY : src/UI/UI.i

# target to preprocess a source file
src/UI/UI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/UI.cpp.i
.PHONY : src/UI/UI.cpp.i

src/UI/UI.s: src/UI/UI.cpp.s
.PHONY : src/UI/UI.s

# target to generate assembly for a file
src/UI/UI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/UI.cpp.s
.PHONY : src/UI/UI.cpp.s

src/UI/Widgets/Checkbox.o: src/UI/Widgets/Checkbox.cpp.o
.PHONY : src/UI/Widgets/Checkbox.o

# target to build an object file
src/UI/Widgets/Checkbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/Checkbox.cpp.o
.PHONY : src/UI/Widgets/Checkbox.cpp.o

src/UI/Widgets/Checkbox.i: src/UI/Widgets/Checkbox.cpp.i
.PHONY : src/UI/Widgets/Checkbox.i

# target to preprocess a source file
src/UI/Widgets/Checkbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/Checkbox.cpp.i
.PHONY : src/UI/Widgets/Checkbox.cpp.i

src/UI/Widgets/Checkbox.s: src/UI/Widgets/Checkbox.cpp.s
.PHONY : src/UI/Widgets/Checkbox.s

# target to generate assembly for a file
src/UI/Widgets/Checkbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/Checkbox.cpp.s
.PHONY : src/UI/Widgets/Checkbox.cpp.s

src/UI/Widgets/ColorRotationEditor.o: src/UI/Widgets/ColorRotationEditor.cpp.o
.PHONY : src/UI/Widgets/ColorRotationEditor.o

# target to build an object file
src/UI/Widgets/ColorRotationEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/ColorRotationEditor.cpp.o
.PHONY : src/UI/Widgets/ColorRotationEditor.cpp.o

src/UI/Widgets/ColorRotationEditor.i: src/UI/Widgets/ColorRotationEditor.cpp.i
.PHONY : src/UI/Widgets/ColorRotationEditor.i

# target to preprocess a source file
src/UI/Widgets/ColorRotationEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/ColorRotationEditor.cpp.i
.PHONY : src/UI/Widgets/ColorRotationEditor.cpp.i

src/UI/Widgets/ColorRotationEditor.s: src/UI/Widgets/ColorRotationEditor.cpp.s
.PHONY : src/UI/Widgets/ColorRotationEditor.s

# target to generate assembly for a file
src/UI/Widgets/ColorRotationEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/ColorRotationEditor.cpp.s
.PHONY : src/UI/Widgets/ColorRotationEditor.cpp.s

src/UI/Widgets/HiddenInput.o: src/UI/Widgets/HiddenInput.cpp.o
.PHONY : src/UI/Widgets/HiddenInput.o

# target to build an object file
src/UI/Widgets/HiddenInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/HiddenInput.cpp.o
.PHONY : src/UI/Widgets/HiddenInput.cpp.o

src/UI/Widgets/HiddenInput.i: src/UI/Widgets/HiddenInput.cpp.i
.PHONY : src/UI/Widgets/HiddenInput.i

# target to preprocess a source file
src/UI/Widgets/HiddenInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/HiddenInput.cpp.i
.PHONY : src/UI/Widgets/HiddenInput.cpp.i

src/UI/Widgets/HiddenInput.s: src/UI/Widgets/HiddenInput.cpp.s
.PHONY : src/UI/Widgets/HiddenInput.s

# target to generate assembly for a file
src/UI/Widgets/HiddenInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/HiddenInput.cpp.s
.PHONY : src/UI/Widgets/HiddenInput.cpp.s

src/UI/Widgets/Input.o: src/UI/Widgets/Input.cpp.o
.PHONY : src/UI/Widgets/Input.o

# target to build an object file
src/UI/Widgets/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/Input.cpp.o
.PHONY : src/UI/Widgets/Input.cpp.o

src/UI/Widgets/Input.i: src/UI/Widgets/Input.cpp.i
.PHONY : src/UI/Widgets/Input.i

# target to preprocess a source file
src/UI/Widgets/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/Input.cpp.i
.PHONY : src/UI/Widgets/Input.cpp.i

src/UI/Widgets/Input.s: src/UI/Widgets/Input.cpp.s
.PHONY : src/UI/Widgets/Input.s

# target to generate assembly for a file
src/UI/Widgets/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/Input.cpp.s
.PHONY : src/UI/Widgets/Input.cpp.s

src/UI/Widgets/NumericInput.o: src/UI/Widgets/NumericInput.cpp.o
.PHONY : src/UI/Widgets/NumericInput.o

# target to build an object file
src/UI/Widgets/NumericInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/NumericInput.cpp.o
.PHONY : src/UI/Widgets/NumericInput.cpp.o

src/UI/Widgets/NumericInput.i: src/UI/Widgets/NumericInput.cpp.i
.PHONY : src/UI/Widgets/NumericInput.i

# target to preprocess a source file
src/UI/Widgets/NumericInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/NumericInput.cpp.i
.PHONY : src/UI/Widgets/NumericInput.cpp.i

src/UI/Widgets/NumericInput.s: src/UI/Widgets/NumericInput.cpp.s
.PHONY : src/UI/Widgets/NumericInput.s

# target to generate assembly for a file
src/UI/Widgets/NumericInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/NumericInput.cpp.s
.PHONY : src/UI/Widgets/NumericInput.cpp.s

src/UI/Widgets/PieceEditor.o: src/UI/Widgets/PieceEditor.cpp.o
.PHONY : src/UI/Widgets/PieceEditor.o

# target to build an object file
src/UI/Widgets/PieceEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/PieceEditor.cpp.o
.PHONY : src/UI/Widgets/PieceEditor.cpp.o

src/UI/Widgets/PieceEditor.i: src/UI/Widgets/PieceEditor.cpp.i
.PHONY : src/UI/Widgets/PieceEditor.i

# target to preprocess a source file
src/UI/Widgets/PieceEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/PieceEditor.cpp.i
.PHONY : src/UI/Widgets/PieceEditor.cpp.i

src/UI/Widgets/PieceEditor.s: src/UI/Widgets/PieceEditor.cpp.s
.PHONY : src/UI/Widgets/PieceEditor.s

# target to generate assembly for a file
src/UI/Widgets/PieceEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/UI/Widgets/PieceEditor.cpp.s
.PHONY : src/UI/Widgets/PieceEditor.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Stakken.dir/build.make CMakeFiles/Stakken.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Client"
	@echo "... Server"
	@echo "... Stakken"
	@echo "... include/gl3w.o"
	@echo "... include/gl3w.i"
	@echo "... include/gl3w.s"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/Assets/Assets.o"
	@echo "... src/Assets/Assets.i"
	@echo "... src/Assets/Assets.s"
	@echo "... src/Assets/BGShader.o"
	@echo "... src/Assets/BGShader.i"
	@echo "... src/Assets/BGShader.s"
	@echo "... src/Assets/Font.o"
	@echo "... src/Assets/Font.i"
	@echo "... src/Assets/Font.s"
	@echo "... src/Assets/Sound.o"
	@echo "... src/Assets/Sound.i"
	@echo "... src/Assets/Sound.s"
	@echo "... src/Assets/Sounds.o"
	@echo "... src/Assets/Sounds.i"
	@echo "... src/Assets/Sounds.s"
	@echo "... src/Assets/Texture.o"
	@echo "... src/Assets/Texture.i"
	@echo "... src/Assets/Texture.s"
	@echo "... src/Challenges/Challenges.o"
	@echo "... src/Challenges/Challenges.i"
	@echo "... src/Challenges/Challenges.s"
	@echo "... src/Data/Identity.o"
	@echo "... src/Data/Identity.i"
	@echo "... src/Data/Identity.s"
	@echo "... src/Game/Board.o"
	@echo "... src/Game/Board.i"
	@echo "... src/Game/Board.s"
	@echo "... src/Game/ClientLobby.o"
	@echo "... src/Game/ClientLobby.i"
	@echo "... src/Game/ClientLobby.s"
	@echo "... src/Game/Demo.o"
	@echo "... src/Game/Demo.i"
	@echo "... src/Game/Demo.s"
	@echo "... src/Game/DemoPlayer.o"
	@echo "... src/Game/DemoPlayer.i"
	@echo "... src/Game/DemoPlayer.s"
	@echo "... src/Game/DemoRecorder.o"
	@echo "... src/Game/DemoRecorder.i"
	@echo "... src/Game/DemoRecorder.s"
	@echo "... src/Game/Game.o"
	@echo "... src/Game/Game.i"
	@echo "... src/Game/Game.s"
	@echo "... src/Game/LocalLobby.o"
	@echo "... src/Game/LocalLobby.i"
	@echo "... src/Game/LocalLobby.s"
	@echo "... src/Game/Piece.o"
	@echo "... src/Game/Piece.i"
	@echo "... src/Game/Piece.s"
	@echo "... src/Game/Randomizers/SimonRandomizer.o"
	@echo "... src/Game/Randomizers/SimonRandomizer.i"
	@echo "... src/Game/Randomizers/SimonRandomizer.s"
	@echo "... src/Game/Randomizers/XoroshiroRandomizer.o"
	@echo "... src/Game/Randomizers/XoroshiroRandomizer.i"
	@echo "... src/Game/Randomizers/XoroshiroRandomizer.s"
	@echo "... src/Gamemodes/Gamemodes.o"
	@echo "... src/Gamemodes/Gamemodes.i"
	@echo "... src/Gamemodes/Gamemodes.s"
	@echo "... src/Input/Input.o"
	@echo "... src/Input/Input.i"
	@echo "... src/Input/Input.s"
	@echo "... src/Input/InputProfile.o"
	@echo "... src/Input/InputProfile.i"
	@echo "... src/Input/InputProfile.s"
	@echo "... src/Input/Keyboard.o"
	@echo "... src/Input/Keyboard.i"
	@echo "... src/Input/Keyboard.s"
	@echo "... src/Networking/Client.o"
	@echo "... src/Networking/Client.i"
	@echo "... src/Networking/Client.s"
	@echo "... src/Networking/Server.o"
	@echo "... src/Networking/Server.i"
	@echo "... src/Networking/Server.s"
	@echo "... src/Rendering/RenderGame.o"
	@echo "... src/Rendering/RenderGame.i"
	@echo "... src/Rendering/RenderGame.s"
	@echo "... src/Rendering/Renderer.o"
	@echo "... src/Rendering/Renderer.i"
	@echo "... src/Rendering/Renderer.s"
	@echo "... src/Rendering/ScreenQuad.o"
	@echo "... src/Rendering/ScreenQuad.i"
	@echo "... src/Rendering/ScreenQuad.s"
	@echo "... src/Rendering/Shader.o"
	@echo "... src/Rendering/Shader.i"
	@echo "... src/Rendering/Shader.s"
	@echo "... src/States/ChallengePlayState.o"
	@echo "... src/States/ChallengePlayState.i"
	@echo "... src/States/ChallengePlayState.s"
	@echo "... src/States/ChallengeSelectState.o"
	@echo "... src/States/ChallengeSelectState.i"
	@echo "... src/States/ChallengeSelectState.s"
	@echo "... src/States/LobbyState.o"
	@echo "... src/States/LobbyState.i"
	@echo "... src/States/LobbyState.s"
	@echo "... src/States/LoginState.o"
	@echo "... src/States/LoginState.i"
	@echo "... src/States/LoginState.s"
	@echo "... src/States/MenuState.o"
	@echo "... src/States/MenuState.i"
	@echo "... src/States/MenuState.s"
	@echo "... src/States/RoomSelectState.o"
	@echo "... src/States/RoomSelectState.i"
	@echo "... src/States/RoomSelectState.s"
	@echo "... src/States/SettingsState.o"
	@echo "... src/States/SettingsState.i"
	@echo "... src/States/SettingsState.s"
	@echo "... src/Text/Font.o"
	@echo "... src/Text/Font.i"
	@echo "... src/Text/Font.s"
	@echo "... src/UI/Node.o"
	@echo "... src/UI/Node.i"
	@echo "... src/UI/Node.s"
	@echo "... src/UI/UI.o"
	@echo "... src/UI/UI.i"
	@echo "... src/UI/UI.s"
	@echo "... src/UI/Widgets/Checkbox.o"
	@echo "... src/UI/Widgets/Checkbox.i"
	@echo "... src/UI/Widgets/Checkbox.s"
	@echo "... src/UI/Widgets/ColorRotationEditor.o"
	@echo "... src/UI/Widgets/ColorRotationEditor.i"
	@echo "... src/UI/Widgets/ColorRotationEditor.s"
	@echo "... src/UI/Widgets/HiddenInput.o"
	@echo "... src/UI/Widgets/HiddenInput.i"
	@echo "... src/UI/Widgets/HiddenInput.s"
	@echo "... src/UI/Widgets/Input.o"
	@echo "... src/UI/Widgets/Input.i"
	@echo "... src/UI/Widgets/Input.s"
	@echo "... src/UI/Widgets/NumericInput.o"
	@echo "... src/UI/Widgets/NumericInput.i"
	@echo "... src/UI/Widgets/NumericInput.s"
	@echo "... src/UI/Widgets/PieceEditor.o"
	@echo "... src/UI/Widgets/PieceEditor.i"
	@echo "... src/UI/Widgets/PieceEditor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

